#! /bin/bash
#======================================================================================================#
#
#     ___       ___       ___       ___       ___       ___       ___       ___   
#    /\  \     /\__\     /\__\     /\  \     /\  \     /\  \     /\  \     /\  \  
#   /::\  \   /:/  /    /:/ _/_   /::\  \   /::\  \   _\:\  \    \:\  \   /::\  \ 
#  /::\:\__\ /:/__/    /:/_/\__\ /:/\:\__\ /::\:\__\ /\/::\__\   /::\__\ /::\:\__\
#  \/\:\/__/ \:\  \    \:\/:/  / \:\/:/  / \;:::/  / \::/\/__/  /:/\/__/ \:\:\/  /
#     \/__/   \:\__\    \::/  /   \::/  /   |:\/__/   \:\__\    \/__/     \:\/  / 
#              \/__/     \/__/     \/__/     \|__|     \/__/               \/__/  
#
#
# AUTHOR:
# 	Francesco A. Franco
#		- https://github.com/ffrancoa
#
# 
# ORIGINAL AUTHOR:
#     Bryan Jenks
#         - www.bryanjenks.xyz
#         - https://github.com/tallguyjenks/flash.sh
#
# ORIGINAL PROJECT:
#	Fla.sh by Bryan Jenks
#		- www.bryanjenks.xyz
#		- https://github.com/tallguyjenks/flash.sh
#
# PURPOSE:
#	To have a CLI tool to learn more about Geotechnical Engineering.
#
# VISION (by Bryan Jenks):
#	"The goal i have for this script is a basic level emulation of ANKI to where i have a way to
#	 keep track of a score for each item in each selected deck so that it can pick from a selection
#	 of the lowest scoring items and shuf them to the user for reenforcement of active recall."
#
# DEPENDENCIES:
#	bat - https://github.com/sharkdp/bat
#	fzf - https://github.com/junegunn/fzf
#======================================================================================================#

VERSION="1.0"

# USER CUSTOMIZABLE VARIABLES
CARD_POOL_SIZE=5        	# How large the pool size is for shuf to draw from
SEARCH_DEPTH=10          	# How many levels to recursively search for .csv's in .local/share/fluorite
PREVIEWER='bat'         	# What fzf previewer to use when searching through decks
CURR_DECK_DISPLAY="file"	# Options are 'file' or 'path'

# ANSI FOREGROUND ESCAPE COLORS
RED='\033[0;31m'
LRED='\033[1;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
LGREEN='\033[1;32m'
LBLUE='\033[1;34m'
LMAGENTA='\033[1;35m'
CYAN='\033[0;36m'
LCYAN='\033[1;36m'
ORANGE='\033[0;33m'
LGREY='\033[0;37m'
WHITE='\033[1;37m'
NC='\033[0m' # No Color

# ANSI BACKGROUND ESCAPE COLORS
WHITEBG='\033[1;47m'
CYANBG='\033[1;46m'
# FONT FORMAT EXCAPE CODES
BOLD='\e[1m'

# Choose your favourite BAT theme using bat --list-themes
BAT_THEME="gruvbox-dark"

# Remember User's Starting Directory
PWD="$(pwd)"
# Terminal rows and columns
ROWS="$(tput lines)"
COLS="$(tput cols)"
# Prefer XDG Configuration before hard coded file paths
OS="$(uname)"
case "$OS" in
"Darwin") DIR="${XDG_DATA_HOME:-$HOME/Library/Application Support}/fluorite" && alias shuf=gshuf ;;
"Linux") DIR="${XDG_DATA_HOME:-$HOME/.local/share}/fluorite" ;;
*) DIR="${XDG_DATA_HOME:-$HOME/.local/share}/fluorite" ;;
esac
# Where the example deck will be placed and named
EXAMPLE_DECK="$DIR/deck.csv"
# Track High score
HIGH_SCORE="$DIR/.highscore"
# Track number of cards reviewed per session
REVIEW_LOG="$DIR/.reviews"
# Iterator for Count of cards reveiwed
COUNTER=0
# Success message of setup process
DIR_MADE_MSG="
Your ${LRED}$DIR${NC} directory has been made and
your ${ORANGE}deck.csv${NC} file is ready for you to enter your flashcard data
If you want to see information about ${LBLUE}Fluorite${NC} then use the option
${BLUE}fluorite -i${NC}.
"
# User has .local/share directory but no decks inside
NO_DECKS="
No decks were found, please make a new deck
using ${ORANGE}:${NC} as a delimiter in a ${ORANGE}.csv${NC} file in
the ${LRED}$DIR${NC} directory.

An example of a card:
${GREEN}Math:What is the square root of 4?:2:0${NC}
"
# The example flashcard deck to be made
DECK_TEMPLATE="History:When was the declaration of independence signed?:1776:0
Math:What is the square root of 4?:2:4
Science:What is the charge on a proton?:Positive 1:2
Philosophy:What was Socrates known as?:The Gadfly of Athens:0
Programming:What is the typical starting index of an array?:0:5
History:What did Abraham Lincoln typically keep in his hat?:Mail:0
Math:What is the value of PI to 2 decimal places?:3.14:4
Science:What is the charge on an electron?:Negative 1:3
Programming:What does OOP stand for?:Object Oriented Programming:2
History:What did Socrates drink to commit suicide?:Hemlock Tea:2
Math:What is the general equation for the slope of a line?:y=mx+b:4
Science:What is the charge on a neutron?:Neutral:1
Programming:What is Vim?:God's Text Editor:999
History:What were the British known by during the American Revolution?:The Redcoats:1
Math:What is the value of this equation - log10(100)?:2:0
Science:What are protons and neutrons made of?:quarks:5
Programming:What does RAM stand for?:Random Access Memory:1
History:What was the year 2000 also known as?:Y2K:0
Math:What is the formula for the mean?:Sum/count:4
Science:What is cold?:The absense of heat:3
Programming:What languages are the worst?:Proprietary:999
History:When did man land on the moon?:1969:4
Math:10^3=?:1000:1
Science:The _____ ______ Project mapped all of man's genes.:Human Genome:3
Programming:What is the best computer to program on?:Thinkpad:999
History:When was fla.sh created?:April 2020:999
Math:What do you call a number only divisible by itself and 1?:Prime:0
Science:What is the distance between the Earth and Sol called?:An Astronomical Unit (AU):1
Programming:What is the best operating system?:Arch, because BTW i run Arch:999"

# Define setup process in a function and create necessary files for user
setup() {
    mkdir "$DIR" &&
        touch {"$EXAMPLE_DECK","$HIGH_SCORE","$REVIEW_LOG"} &&
        echo "$DECK_TEMPLATE" >>"$EXAMPLE_DECK" &&
        echo -e "$DIR_MADE_MSG"
}

# Test if .local/share exists and wether to offer setup process
if [ ! -d "$DIR" ]; then
    echo -e "No ${LRED}$DIR${NC} directory, make it? ${LGREEN}Y${NC}/${LRED}N${NC}"
    # shellcheck disable=SC2162
    read RESPONSE
    case "$RESPONSE" in
    [QqNn]) exit 0 ;;
    [Yy]) setup && exit 0 ;;
    *) >&2 echo -e "invalid choice, please select either ${LGREEN}y${NC} or ${LRED}n${NC}" && exit 1 ;;
    esac
fi

# go to the flashcard decks directory
cd "$DIR" || exit 1

# If there are no flashcard decks available return user to starting location
# while also displaying explanatory text of issue
[ "$(find . -maxdepth "$SEARCH_DEPTH" -iname "*.csv" | wc -l)" = 0 ] &&
    >&2 echo -e "$NO_DECKS" && exit 1

# if highscore file was removed, remake it.
[ ! -e "$HIGH_SCORE" ] && touch "$HIGH_SCORE"

# if reviewed file was removed, remake it.
[ ! -e "$REVIEW_LOG" ] && touch "$REVIEW_LOG"

print_usage() {
    echo -e "\n${LCYAN}Fluorite --- Geotechnical Flash cards by Francesco A. Franco, originally by Bryan Jenks${NC} ${LBLUE}<ffrancoa@uni.pe>${NC}\n\n${YELLOW}${BOLD}Usage:${NC}\n\t${GREEN}fluorite -h:${NC} Print this help text\n\t${GREEN}fluorite -i:${NC} Print Information about the flashcard system\n\t${GREEN}fluorite -v:${NC} Print version Number\n\t${GREEN}fluorite -p [BINARY]:${NC} Change the previewer when selecting decks.\n\t\tDefault: ${GREEN}bat${NC}\n\t\tSupported: ${GREEN}bat${NC}, ${GREEN}cat${NC}\n"
}

print_info() {
    echo -e "\nThis flash card system works via colon ${YELLOW}:${NC} seperated ${YELLOW}.csv${NC} files\n
with entries that look like this: ${LGREY}Reference:Question:Answer:0${NC}\n
These ${YELLOW}.csv${NC} files should be stored in your

\t${YELLOW}\$XDG_DATA_HOME/fluorite${NC}
i==============================================================#
OR
\t${YELLOW}~/.local/share/fluorite${NC} for Linux
\t${YELLOW}~/Library/Application Support/fluorite${NC} for mac
-------------------------------------------------------------------------------
${LCYAN}Exiting:${NC}\n
\tYou can exit the application at any time by pressing either ${RED}q${NC} or ${RED}Q${NC}

${LCYAN}Usage:${NC}\n
\tYou will first be prompted with a question and will need to press ${RED}[Enter]${NC}
\tto reveal the answer. Once the answer is revealed you will need to either
\tquit, or give a rating to how difficult the question was.

${LCYAN}The Scoring System:${NC}\n
\tThe last field in the ${YELLOW}.csv${NC} files is the current point score of the 'card'
\tEvery time you rate a card the point score will either increase, decrease,
\tor stay the same. zero is the lowest value, and the upper limit is over
\t100 billion.

\t${CYAN}Scoring Results:${NC}
\t\t[${LRED}Hard${NC}]\t\t-2 points
\t\t[${LMAGENTA}Difficult${NC}]\t-1 point
\t\t[${YELLOW}Normal${NC}]\tNo Change
\t\t[${LBLUE}Mild${NC}]\t\t+1 point
\t\t[${LGREEN}Easy${NC}]\t\t+2 points

\tThe cards with the lowest scores (you scored them as ${LRED}Hard${NC}/${LMAGENTA}Difficult${NC}) are
\tsorted to the top, a pool of them are picked and from that pool 1 card is
\trandomly drawn. As you become more familair with the material and rate it
\tas easier, the point values will go up and the cards will appear less
\tfrequently making room for those cards that are still difficult and have
\tlower point values.

    It is a good idea to start all cards off at ${YELLOW}0${NC} initially so that they all
    have an equal chance of being drawn initially.
"
}

while getopts 'hivp:' flag; do
    case "${flag}" in
    h) print_usage && exit 0 ;;
    i) print_info && exit 0 ;;
    v) echo -e "\n${YELLOW}Fluorite - Current Version:${NC} ${RED} ${VERSION} ${NC}\n" && exit 0 ;;
    p) { [[ $(command -v "$OPTARG" 2>&1) ]] && PREVIEWER=$OPTARG; } || >&2 echo "Unable to find previewer $OPTARG. Exiting..." && exit 1 ;;
    *) print_usage && exit 1 ;;
    esac
done

# Set some parameters for preview command used by FZF
while [ -z "$PREVIEWER_PARAMTERS" ]; do
    case "$PREVIEWER" in
    bat) PREVIEWER_PARAMTERS="--theme='${BAT_THEME}' --style=numbers --color=always --line-range :${ROWS} {}" ;;
    cat) PREVIEWER_PARAMTERS="-b" ;;
    *) echo -e "${RED}$PREVIEWER${NC} is not a valid previewer. Use '${GREEN}bat${NC}' or '${GREEN}cat${NC}'. Falling back on default...\n" && read -r -s -p 'Press [Enter] to continue...' && echo -e "\n" && PREVIEWER='bat' ;;
    esac
done


# Show pretty FZF preview of decks using $PREVIEWER. Default: BAT
DECK="$(find . -maxdepth "$SEARCH_DEPTH" -iname "*.csv" | fzf --preview "$PREVIEWER $PREVIEWER_PARAMTERS" \
															  --delimiter : \
															  --header="טּ  Choose a Deck" \
															  --header-first \
															  --preview-window "bottom,70%" \
															  --color "prompt:3,hl+:6,fg+:2,gutter:2,pointer:2,header:6:bold")"

# Get current deck name for display
case "$CURR_DECK_DISPLAY" in
file) CURRENT_DECK="$(echo "$DECK" | awk -F/ '{print $NF}')" ;;
path) CURRENT_DECK="$DECK" ;;
*) CURRENT_DECK="$(echo "$DECK" | awk -F/ '{print $NF}')" ;;
esac

# The top part of the flash display so that code is not duplicated
print_head() {
    QUESTION=$(echo "${q[1]}")	

	# Prints the header centered
	HEADER="  Fluorite - Geotechnical Flash Cards  "
	HEADER_PADDING_LEFT=$(awk "BEGIN {print int(($COLS - ${#HEADER}) / 2)}")
   	HEADER_PADDING_RIGHT=$(echo "$(($COLS - $HEADER_PADDING_LEFT - ${#HEADER}))")

   	echo -e -n "${CYANBG}"
 	printf "%*s" $HEADER_PADDING_LEFT
    echo -n "$HEADER"
 	printf "%*s" $HEADER_PADDING_RIGHT
	echo -e "${NC}"

	# Prints the subheaders centered also
	SUBTITLES_PADDING=$((($COLS - 25) / 2))

	SUBTITLE_1="${ORANGE}${BOLD}﬷  Current Deck:${BOLD}${NC} $(basename -s .csv "$CURRENT_DECK")"
	printf "\n%*s" $SUBTITLES_PADDING
	echo -e -n "${SUBTITLE_1}"

	SUBTITLE_2="${ORANGE}${BOLD}履 Cards Reviewed:${BOLD}${NC} $COUNTER"
	printf "\n%*s" $SUBTITLES_PADDING
	echo -e -n "${SUBTITLE_2}"

	SUBTITLE_3="${ORANGE}${BOLD}  High Score:${BOLD}${NC} $(cat "$HIGH_SCORE")"
	printf "\n%*s" $SUBTITLES_PADDING
	echo -e -n "${SUBTITLE_3}"
	
	SUBTITLE_4="${ORANGE}${BOLD}  Avg Review:${BOLD}${NC} $(awk '{ sum += $7; n++ } END { if (n > 0) print int(sum / n) ; }' "$REVIEW_LOG")"
	printf "\n%*s" $SUBTITLES_PADDING
	echo -e -n "${SUBTITLE_4}"

	SUBTITLE_5="${LGREY}${BOLD}  Reference:${BOLD}${NC} ${q[0]}"
	printf "\n\n%*s" $SUBTITLES_PADDING
	echo -e "${SUBTITLE_5}\n"

	for ((i = 0; i < $COLS; i++))
	do
		echo -n -
	done

	# Print question
	QUESTION_PADDING_LEFT=$(awk "BEGIN {print int(($COLS - ${#QUESTION}) / 2)}")

	printf "\n\n%*s" $QUESTION_PADDING_LEFT
	echo -e "$QUESTION\n"
}

# Creating new entries in the log for the average score generation
add_usage_entry() {
    if [ ! "$COUNTER" = 0 ]; then
        # Create a New Entry
        TIME_STAMP=$(date +"%Y%m%d %H:%M:%S")
        printf -v ENTRY "TimeStamp: %s Deck: %s cardsReviewed: %s" "$TIME_STAMP" "$CURRENT_DECK" "$COUNTER"
        echo "$ENTRY" >>"$REVIEW_LOG"
    fi
}

# If no deck is selected in fzf menu
# return user to start location
# and exit quietly
[ -z "$DECK" ] && clear && exit 1

main() {
    IFS=$':'
    # shellcheck disable=SC2162
    read -a q <<<"$(sort "$DECK" -n --field-separator=: --key=4 | head -n "$CARD_POOL_SIZE" | shuf -n 1)"
    clear

    print_head

	CONTINUE=" Press [Enter] to continue "
	CONT_PADDING_LEFT=$(awk "BEGIN {print int(($COLS - ${#CONTINUE}) / 2)}")
	CONT_PADDING_RIGHT=$(echo "$(($COLS - $CONT_PADDING_LEFT - ${#CONTINUE}))")

	echo -e -n "${LGREY}"
	printf "%*s" $CONT_PADDING_LEFT | tr ' ' "-"
	echo -n "$CONTINUE"
	printf "%*s" $CONT_PADDING_RIGHT | tr ' ' "-"
	echo -e "${NC}"

    # shellcheck disable=SC2162
    read -sn 1 NEXT
    while [ ! "$NEXT" = "" ] && [ ! "$NEXT" = q ] && [ ! "$NEXT" = Q ]; do
        # shellcheck disable=SC2162
        read -sn 1 NEXT
    done
    clear

	# Refresh terminal after pressing [Enter]
    print_head

	# Separator for answer
	echo -e -n "${LGREY}"

	for ((i = 0; i < $COLS; i++))
    do
    	echo -n -
    done

	echo -e "${NC}"

	# Show answer
    { [ "$NEXT" = q ] || [ "$NEXT" = Q ]; } && add_usage_entry && clear && exit 0

    ANSWER=$(echo "${q[2]}")

	echo -e -n "${GREEN}${BOLD}"
	printf "\n%*s\n" $(((${#ANSWER} + $COLS + 1) / 2)) "$ANSWER"
	echo -e "${NC}"

	# Separator for answer punctuation
 	echo -e -n "${WHITEBG}${WHITE}"

    for ((i = 0; i < $COLS; i++))
    do
	    echo -n =
	done

    echo -e "${NC}"

	# User Score
	FINAL_QUESTION="How Difficult Was This Question?"

	echo -e -n "${LGREY}"
    printf "\n%*s\n" $(((${#FINAL_QUESTION} + $COLS + 1) / 2)) "$FINAL_QUESTION"
    echo -e "${NC}"

	SCORE_PADDING=$((($COLS - 59) / 2))

	printf "%*s" $SCORE_PADDING
	echo -e "${LRED}Hard${NC} [1]   ${LMAGENTA}Difficult${NC} [2]   ${YELLOW}Normal${NC} [3]   ${LBLUE}Mild${NC} [4]   ${LGREEN}Easy${NC} [5]"

	QUERY_PADDING=$((($COLS - 44) / 2))

	printf "\n%*s" $QUERY_PADDING
	echo -e -n "${LGREY}Select a number to continue, or${NC} ${LRED}Q${NC} ${LGREY}to quit...${NC}"

    # shellcheck disable=SC2162
    read -sn 1 DIFFICULTY_SCORE
    while [[ ! "$DIFFICULTY_SCORE" =~ [12345qQ] ]]; do
        # shellcheck disable=SC2162
        read -sn 1 DIFFICULTY_SCORE
    done
    { [ "$DIFFICULTY_SCORE" = q ] || [ "$DIFFICULTY_SCORE" = Q ]; } &&
        add_usage_entry && clear && exit 0
    clear

    COUNTER="$((COUNTER + 1))" # Increment count for card review count increment

	# Revisión de puntaje por pregunta

    if [ "${q[3]}" = 0 ]; then
        NEW_ITEM_SCORE=0
        case "$DIFFICULTY_SCORE" in
        [123]) NEW_ITEM_SCORE=0 ;; # HARD, DIFFICULT OR NORMAL
        4) NEW_ITEM_SCORE=1 ;; # MILD
        5) NEW_ITEM_SCORE=2 ;; # EASY
        esac

    elif [ "${q[3]}" = 1 ]; then
        case "$DIFFICULTY_SCORE" in
        1) NEW_ITEM_SCORE=0 ;; # HARD
        2) NEW_ITEM_SCORE=0 ;; # DIFFICULT
        3) NEW_ITEM_SCORE=1 ;; # NORMAL
        4) NEW_ITEM_SCORE=2 ;; # MILD
        5) NEW_ITEM_SCORE=3 ;; # EASY
        esac
    else
        case "$DIFFICULTY_SCORE" in
        1) NEW_ITEM_SCORE="$((q[3] - 2))" ;; #HARD
        2) NEW_ITEM_SCORE="$((q[3] - 1))" ;; # DIFFICULTY
        3) NEW_ITEM_SCORE="${q[3]}" ;; # NORMAL
        4) NEW_ITEM_SCORE="$((q[3] + 1))" ;; # MILD
        5) NEW_ITEM_SCORE="$((q[3] + 2))" ;; # EASY
        esac
    fi

    # Update item score for each flashcard item
    ## Remove forward slashes in the Questions and answers

    QUESTION_REGEX="$(sed "s/\(\/\|\[\|\]\|\*\)/\\\\\1/g" <<<"${q[1]}")"
    ANSWER_REGEX="$(sed "s/\(\/\|\[\|\]\|\*\)/\\\\\1/g" <<<"${q[2]}")"
    sed -i "s/${q[0]}:$QUESTION_REGEX:$ANSWER_REGEX:${q[3]}/${q[0]}:$QUESTION_REGEX:$ANSWER_REGEX:$NEW_ITEM_SCORE/g" "$DECK"
    
    # If no highscore currently set, set it.
    [ -z "$(cat "$HIGH_SCORE")" ] && echo "$COUNTER" >"$HIGH_SCORE"

    # If Cards Reviewed > Current High Score, Update
    [ "$COUNTER" -gt "$(cat "$HIGH_SCORE")" ] && echo "$COUNTER" >"$HIGH_SCORE"
}

while true; do
    main
done
